import express from "express";import dotenv from "dotenv";import pg from "pg";import bcrypt from "bcryptjs";import jwt from "jsonwebtoken";import cookieParser from "cookie-parser";import crypto from "crypto";import path from "path";import {fileURLToPath} from "url";
dotenv.config();const {Pool}=pg,app=express(),port=process.env.PORT||3000,__filename=fileURLToPath(import.meta.url),__dirname=path.dirname(__filename),pub=path.join(__dirname,"public"),pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false}});
app.use(express.json({limit:"32kb"}));app.use(cookieParser());
const norm=v=>{let p=String(v||"").replace(/\D/g,"");if(p.startsWith("0"))p="62"+p.slice(1);if(!p.startsWith("62"))p="62"+p;if(!/^62\d{8,15}$/.test(p))throw Error("Nomor WhatsApp tidak valid.");return "+"+p};
const session=(res,u)=>res.cookie("anakasuh_session",jwt.sign({sub:String(u.id),role:u.role},process.env.JWT_SECRET,{expiresIn:"24h"}),{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"lax",maxAge:86400000,path:"/"});
async function wa(to,text){let v=process.env.WHATSAPP_API_VERSION||"v23.0",r=await fetch(`https://graph.facebook.com/${v}/${process.env.WHATSAPP_PHONE_NUMBER_ID}/messages`,{method:"POST",headers:{Authorization:`Bearer ${process.env.WHATSAPP_TOKEN}`,"Content-Type":"application/json"},body:JSON.stringify({messaging_product:"whatsapp",to:to.replace("+",""),type:"text",text:{body:text}})});if(!r.ok)throw Error("WhatsApp API gagal mengirim OTP.")}
function auth(req,res,next){try{req.user=jwt.verify(req.cookies.anakasuh_session,process.env.JWT_SECRET);next()}catch{return res.status(401).json({error:"Belum login."})}}
function adminAuth(req,res,next){try{req.user=jwt.verify(req.cookies.anakasuh_session,process.env.JWT_SECRET);if(req.user.role!=="ADMIN")return res.status(403).json({error:"Akses khusus admin."});next()}catch{return res.status(401).json({error:"Belum login."})}}
app.get("/api/health",async(req,res)=>{try{await pool.query("select 1");res.json({ok:true,db:true})}catch{res.status(500).json({ok:false})}});
app.post("/api/auth/register",async(req,res)=>{try{let{name,phone,role}=req.body,p=norm(phone);if(!name?.trim()||!["CHILD","SPONSOR","ADMIN"].includes(role))return res.status(400).json({error:"Data tidak lengkap."});let q=await pool.query("select id from users where phone_e164=$1",[p]);if(q.rowCount)return res.status(409).json({error:"Nomor sudah terdaftar."});let st=role==="ADMIN"?"PENDING":"PENDING";await pool.query("insert into users(name,phone_e164,role,status) values($1,$2,$3,$4)",[name.trim(),p,role,st]);res.status(201).json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
app.post("/api/auth/whatsapp/request-otp",async(req,res)=>{try{let p=norm(req.body.phone),q=await pool.query("select id,status from users where phone_e164=$1",[p]);if(!q.rowCount)return res.json({ok:true,message:"Jika nomor terdaftar, OTP akan dikirim."});if(q.rows[0].status==="SUSPENDED")return res.status(403).json({error:"Akun ditangguhkan."});await pool.query("delete from whatsapp_otps where phone_e164=$1 or expires_at<now()",[p]);let otp=crypto.randomInt(100000,1000000).toString(),hash=await bcrypt.hash(otp,12);await pool.query("insert into whatsapp_otps(phone_e164,otp_hash,expires_at) values($1,$2,now()+interval '5 minutes')",[p,hash]);await wa(p,`Kode OTP AnakAsuh: ${otp}\nBerlaku 5 menit. Jangan bagikan kode ini.`);res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
app.post("/api/auth/whatsapp/verify-otp",async(req,res)=>{try{let p=norm(req.body.phone),o=String(req.body.otp||"");if(!/^\d{6}$/.test(o))return res.status(400).json({error:"OTP harus 6 digit."});let q=await pool.query("select * from whatsapp_otps where phone_e164=$1 and consumed_at is null and expires_at>now() order by created_at desc limit 1",[p]);if(!q.rowCount)return res.status(401).json({error:"OTP kedaluwarsa."});let x=q.rows[0];if(x.attempts>=5)return res.status(429).json({error:"Terlalu banyak percobaan."});if(!await bcrypt.compare(o,x.otp_hash)){await pool.query("update whatsapp_otps set attempts=attempts+1 where id=$1",[x.id]);return res.status(401).json({error:"OTP salah."})}let u=(await pool.query("select id,name,role,status from users where phone_e164=$1",[p])).rows[0];if(!u)return res.status(401).json({error:"Akun tidak ditemukan."});if(u.status==="SUSPENDED")return res.status(403).json({error:"Akun ditangguhkan."});await pool.query("update whatsapp_otps set consumed_at=now() where id=$1",[x.id]);await pool.query("update users set status='ACTIVE',updated_at=now() where id=$1",[u.id]);session(res,u);res.json({ok:true,redirect:u.role==="ADMIN"?"/admin.html":"/AnakAsuh.html"})}catch(e){res.status(500).json({error:"Verifikasi gagal."})}});
app.get("/api/auth/me",auth,async(req,res)=>{let q=await pool.query("select id,name,phone_e164,role,status from users where id=$1",[req.user.sub]);if(!q.rowCount)return res.status(401).json({error:"Akun tidak ditemukan."});res.json({user:q.rows[0]})});
app.post("/api/auth/logout",(req,res)=>{res.clearCookie("anakasuh_session",{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",path:"/"});res.json({ok:true})});
// === API ADMIN (khusus role ADMIN) ===
app.get("/api/admin/children",adminAuth,async(req,res)=>{try{let q=await pool.query("select * from children order by created_at desc");res.json({children:q.rows})}catch(e){res.status(500).json({error:"Gagal memuat data."})}});
app.post("/api/admin/children",adminAuth,async(req,res)=>{try{let{name,jenjang,poin=0,prestasi="",catatan=""}=req.body;if(!name?.trim()||!["SD","SMP","SMA","PT"].includes(jenjang))return res.status(400).json({error:"Data tidak lengkap."});let q=await pool.query("insert into children(name,jenjang,poin,prestasi,catatan,status) values($1,$2,$3,$4,$5,'ACTIVE') returning *",[name.trim(),jenjang,Number(poin)||0,prestasi,catatan]);res.status(201).json({ok:true,child:q.rows[0]})}catch(e){res.status(400).json({error:e.message})}});
app.put("/api/admin/children/:id",adminAuth,async(req,res)=>{try{let{id}=req.params,{name,jenjang,poin,prestasi,catatan,status,sponsors_count}=req.body;let sets=[],vals=[],i=1;if(name!==undefined){sets.push(`name=$${i++}`);vals.push(name.trim())}if(jenjang!==undefined&&["SD","SMP","SMA","PT"].includes(jenjang)){sets.push(`jenjang=$${i++}`);vals.push(jenjang)}if(poin!==undefined){sets.push(`poin=$${i++}`);vals.push(Number(poin)||0)}if(prestasi!==undefined){sets.push(`prestasi=$${i++}`);vals.push(prestasi)}if(catatan!==undefined){sets.push(`catatan=$${i++}`);vals.push(catatan)}if(status!==undefined&&["PENDING","ACTIVE","SUSPENDED"].includes(status)){sets.push(`status=$${i++}`);vals.push(status)}if(sponsors_count!==undefined){sets.push(`sponsors_count=$${i++}`);vals.push(Number(sponsors_count)||0)}if(!sets.length)return res.status(400).json({error:"Tidak ada perubahan."});sets.push(`updated_at=now()`);vals.push(id);let q=await pool.query(`update children set ${sets.join(",")} where id=$${i} returning *`,vals);if(!q.rowCount)return res.status(404).json({error:"Anak tidak ditemukan."});res.json({ok:true,child:q.rows[0]})}catch(e){res.status(400).json({error:e.message})}});
app.delete("/api/admin/children/:id",adminAuth,async(req,res)=>{try{let{id}=req.params,q=await pool.query("delete from children where id=$1 returning id",[id]);if(!q.rowCount)return res.status(404).json({error:"Anak tidak ditemukan."});res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
app.get("/api/admin/users",adminAuth,async(req,res)=>{try{let q=await pool.query("select id,name,phone_e164,role,status,created_at from users order by created_at desc");res.json({users:q.rows})}catch(e){res.status(500).json({error:"Gagal memuat data."})}});
app.put("/api/admin/users/:id/status",adminAuth,async(req,res)=>{try{let{id}=req.params,{status}=req.body;if(!["PENDING","ACTIVE","SUSPENDED"].includes(status))return res.status(400).json({error:"Status tidak valid."});let q=await pool.query("update users set status=$1,updated_at=now() where id=$2 returning id,name,role,status",[status,id]);if(!q.rowCount)return res.status(404).json({error:"User tidak ditemukan."});res.json({ok:true,user:q.rows[0]})}catch(e){res.status(400).json({error:e.message})}});
app.get("/login.html",(req,res)=>res.sendFile(path.join(pub,"login.html")));app.get("/",(req,res)=>res.redirect("/login.html"));app.get("/app",auth,(req,res)=>res.sendFile(path.join(pub,"AnakAsuh.html")));app.get("/AnakAsuh.html",auth,(req,res)=>res.sendFile(path.join(pub,"AnakAsuh.html")));app.get("/admin.html",adminAuth,(req,res)=>res.sendFile(path.join(pub,"admin.html")));app.use(express.static(pub,{index:false}));if(!process.env.VERCEL){app.listen(port,()=>console.log(`AnakAsuh: http://localhost:${port}`));}export default app;